# graphics_constants.py͏󠄂͏️͏󠄌͏󠄎͏󠄑͏︇͏󠄇
# ----------------͏󠄂͏️͏󠄌͏󠄎͏󠄑͏︇͏󠄇
# Constants for graphics in Go game.
# Author: Porter Zach

from .graphics_utils import format_color

GRID_OFFSET_X = 30
GRID_OFFSET_Y = 30

GRID_BOX_SIZE = 40
GRID_LINE_THICKNESS = 2
GRID_UNIT_SIZE = GRID_BOX_SIZE + GRID_LINE_THICKNESS

STONE_RADIUS = 21
HINT_RADIUS = 5
STONE_HOVER_THICKNESS = 1

BOARD_COLOR = format_color(148, 94, 28)
BACKGROUND_COLOR = BOARD_COLOR
LINE_COLOR = format_color(46, 27, 4)
BOARD_OUTLINE_THICKNESS = 2

SIDEBAR_COLOR = format_color(0, 128, 0)
SIDEBAR_WIDTH = 200
SIDEBAR_BORDER_THICKNESS = 2

WHITE_COLOR = format_color(255, 255, 255)
BLACK_COLOR = format_color(0, 0, 0)
STONE_COLORS = [BLACK_COLOR, WHITE_COLOR]

# Game button parameters
TURN_LABEL_X = -150
TURN_LABEL_Y = 60
PASS_BUTTON_X = -150
PASS_BUTTON_Y = 20
RESIGN_BUTTON_X = -150
RESIGN_BUTTON_Y = -40
FORWARD_BUTTON_X = -150
FORWARD_BUTTON_Y = -120
FF_BUTTON_X = -150
FF_BUTTON_Y = -80
BACKWARD_BUTTON_X = -150
BACKWARD_BUTTON_Y = -160
FB_BUTTON_X = -150
FB_BUTTON_Y = -200